config/routes.rb
Rails.application.routes.draw do

  root :to => "portada#index" #page index by default
  resources :proveedor_servicios
  resources :pagos_publicidads
  resources :pagos_promocions
  resources :clientes
  resources :promocion_eventos
  resources :publicidads
  resources :encuesta
  resources :subcategoria
  resources :categoria
  resources :localidades
  resources :municipios
  resources :provincia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/encuestum.rb
class Encuestum < ApplicationRecord
end

app/models/localidade.rb
class Localidade < ApplicationRecord
  belongs_to :municipios
end

app/models/municipio.rb
class Municipio < ApplicationRecord
  belongs_to :provincia
end

app/models/pagos_promocion.rb
class PagosPromocion < ApplicationRecord
  belongs_to :cliente
  belongs_to :publicidad
end

app/models/pagos_publicidad.rb
class PagosPublicidad < ApplicationRecord
  belongs_to :cliente
  belongs_to :promocionEventos
end

app/models/promocion_evento.rb
class PromocionEvento < ApplicationRecord
  belongs_to :cliente
end

app/models/proveedor_servicio.rb
class ProveedorServicio < ApplicationRecord
  belongs_to :categoria
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/publicidad.rb
class Publicidad < ApplicationRecord
  belongs_to :cliente
end

app/models/subcategorium.rb
class Subcategorium < ApplicationRecord
  belongs_to :categorias
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  before_action :set_municipio, only: [:show, :edit, :update, :destroy]

  # GET /municipios
  # GET /municipios.json
  def index
    @municipios = Municipio.all
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
  end

  # GET /municipios/new
  def new
    @municipio = Municipio.new
  end

  # GET /municipios/1/edit
  def edit
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(municipio_params)

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Municipio was successfully created.' }
        format.json { render :show, status: :created, location: @municipio }
      else
        format.html { render :new }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipios/1
  # PATCH/PUT /municipios/1.json
  def update
    respond_to do |format|
      if @municipio.update(municipio_params)
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipio }
      else
        format.html { render :edit }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio.destroy
    respond_to do |format|
      format.html { redirect_to municipios_url, notice: 'Municipio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipio
      @municipio = Municipio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipio_params
      params.require(:municipio).permit(:nombre, :provincia_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/encuesta_helper.rb
module EncuestaHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/portada_helper.rb
module PortadaHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/helpers/publicidads_helper.rb
module PublicidadsHelper
end

app/views/municipios/_form.html.erb
<%= form_with(model: municipio, local: true) do |form| %>
  <% if municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% municipio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :municipio_nombre %>
  </div>

  <div class="field">
    <%= form.label :provincia_id %>
    <%= form.text_field :provincia_id, id: :municipio_provincia_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing Municipio</h1>

<%= render 'form', municipio: @municipio %>

<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>

app/views/municipios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Provincia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipios.each do |municipio| %>
      <tr>
        <td><%= municipio.nombre %></td>
        <td><%= municipio.provincia %></td>
        <td><%= link_to 'Show', municipio %></td>
        <td><%= link_to 'Edit', edit_municipio_path(municipio) %></td>
        <td><%= link_to 'Destroy', municipio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipio', new_municipio_path %>

app/views/municipios/new.html.erb
<h1>New Municipio</h1>

<%= render 'form', municipio: @municipio %>

<%= link_to 'Back', municipios_path %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @municipio.nombre %>
</p>

<p>
  <strong>Provincia:</strong>
  <%= @municipio.provincia %>
</p>

<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>