config/routes.rb
Rails.application.routes.draw do

  root :to => "portada#index" #page index by default
  resources :proveedor_servicios
  resources :pagos_publicidads
  resources :pagos_promocions
  resources :clientes
  resources :promocion_eventos
  resources :publicidads
  resources :encuesta
  resources :subcategoria
  resources :categoria
  resources :localidades
  resources :municipios
  resources :provincia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/encuestum.rb
class Encuestum < ApplicationRecord
end

app/models/localidade.rb
class Localidade < ApplicationRecord
  belongs_to :municipios
end

app/models/municipio.rb
class Municipio < ApplicationRecord
  belongs_to :provincia
end

app/models/pagos_promocion.rb
class PagosPromocion < ApplicationRecord
  belongs_to :cliente
  belongs_to :publicidad
end

app/models/pagos_publicidad.rb
class PagosPublicidad < ApplicationRecord
  belongs_to :cliente
  belongs_to :promocionEventos
end

app/models/promocion_evento.rb
class PromocionEvento < ApplicationRecord
  belongs_to :cliente
end

app/models/proveedor_servicio.rb
class ProveedorServicio < ApplicationRecord
  belongs_to :categoria
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/publicidad.rb
class Publicidad < ApplicationRecord
  belongs_to :cliente
end

app/models/subcategorium.rb
class Subcategorium < ApplicationRecord
  belongs_to :categorias
end

app/controllers/promocion_eventos_controller.rb
class PromocionEventosController < ApplicationController
  before_action :set_promocion_evento, only: [:show, :edit, :update, :destroy]

  # GET /promocion_eventos
  # GET /promocion_eventos.json
  def index
    @promocion_eventos = PromocionEvento.all
  end

  # GET /promocion_eventos/1
  # GET /promocion_eventos/1.json
  def show
  end

  # GET /promocion_eventos/new
  def new
    @promocion_evento = PromocionEvento.new
  end

  # GET /promocion_eventos/1/edit
  def edit
  end

  # POST /promocion_eventos
  # POST /promocion_eventos.json
  def create
    @promocion_evento = PromocionEvento.new(promocion_evento_params)

    respond_to do |format|
      if @promocion_evento.save
        format.html { redirect_to @promocion_evento, notice: 'Promocion evento was successfully created.' }
        format.json { render :show, status: :created, location: @promocion_evento }
      else
        format.html { render :new }
        format.json { render json: @promocion_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocion_eventos/1
  # PATCH/PUT /promocion_eventos/1.json
  def update
    respond_to do |format|
      if @promocion_evento.update(promocion_evento_params)
        format.html { redirect_to @promocion_evento, notice: 'Promocion evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocion_evento }
      else
        format.html { render :edit }
        format.json { render json: @promocion_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocion_eventos/1
  # DELETE /promocion_eventos/1.json
  def destroy
    @promocion_evento.destroy
    respond_to do |format|
      format.html { redirect_to promocion_eventos_url, notice: 'Promocion evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocion_evento
      @promocion_evento = PromocionEvento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocion_evento_params
      params.require(:promocion_evento).permit(:nombre, :fecha, :descripcion, :periodo_publicacion, :cliente_id, :costo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/encuesta_helper.rb
module EncuestaHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/portada_helper.rb
module PortadaHelper
end

app/helpers/promocion_eventos_helper.rb
module PromocionEventosHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/views/promocion_eventos/_form.html.erb
<%= form_with(model: promocion_evento, local: true) do |form| %>
  <% if promocion_evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocion_evento.errors.count, "error") %> prohibited this promocion_evento from being saved:</h2>

      <ul>
      <% promocion_evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :promocion_evento_nombre %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :promocion_evento_fecha %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :promocion_evento_descripcion %>
  </div>

  <div class="field">
    <%= form.label :periodo_publicacion %>
    <%= form.text_field :periodo_publicacion, id: :promocion_evento_periodo_publicacion %>
  </div>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id, id: :promocion_evento_cliente_id %>
  </div>

  <div class="field">
    <%= form.label :costo %>
    <%= form.text_field :costo, id: :promocion_evento_costo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promocion_eventos/edit.html.erb
<h1>Editing Promocion Evento</h1>

<%= render 'form', promocion_evento: @promocion_evento %>

<%= link_to 'Show', @promocion_evento %> |
<%= link_to 'Back', promocion_eventos_path %>

app/views/promocion_eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promocion Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th>Descripcion</th>
      <th>Periodo publicacion</th>
      <th>Cliente</th>
      <th>Costo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocion_eventos.each do |promocion_evento| %>
      <tr>
        <td><%= promocion_evento.nombre %></td>
        <td><%= promocion_evento.fecha %></td>
        <td><%= promocion_evento.descripcion %></td>
        <td><%= promocion_evento.periodo_publicacion %></td>
        <td><%= promocion_evento.cliente %></td>
        <td><%= promocion_evento.costo %></td>
        <td><%= link_to 'Show', promocion_evento %></td>
        <td><%= link_to 'Edit', edit_promocion_evento_path(promocion_evento) %></td>
        <td><%= link_to 'Destroy', promocion_evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocion Evento', new_promocion_evento_path %>

app/views/promocion_eventos/new.html.erb
<h1>New Promocion Evento</h1>

<%= render 'form', promocion_evento: @promocion_evento %>

<%= link_to 'Back', promocion_eventos_path %>

app/views/promocion_eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @promocion_evento.nombre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @promocion_evento.fecha %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @promocion_evento.descripcion %>
</p>

<p>
  <strong>Periodo publicacion:</strong>
  <%= @promocion_evento.periodo_publicacion %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @promocion_evento.cliente %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @promocion_evento.costo %>
</p>

<%= link_to 'Edit', edit_promocion_evento_path(@promocion_evento) %> |
<%= link_to 'Back', promocion_eventos_path %>