config/routes.rb
Rails.application.routes.draw do

  root :to => "portada#index" #page index by default
  resources :proveedor_servicios
  resources :pagos_publicidads
  resources :pagos_promocions
  resources :clientes
  resources :promocion_eventos
  resources :publicidads
  resources :encuesta
  resources :subcategoria
  resources :categoria
  resources :localidades
  resources :municipios
  resources :provincia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/encuestum.rb
class Encuestum < ApplicationRecord
end

app/models/localidade.rb
class Localidade < ApplicationRecord
  belongs_to :municipios
end

app/models/municipio.rb
class Municipio < ApplicationRecord
  belongs_to :provincia
end

app/models/pagos_promocion.rb
class PagosPromocion < ApplicationRecord
  belongs_to :cliente
  belongs_to :publicidad
end

app/models/pagos_publicidad.rb
class PagosPublicidad < ApplicationRecord
  belongs_to :cliente
  belongs_to :promocionEventos
end

app/models/promocion_evento.rb
class PromocionEvento < ApplicationRecord
  belongs_to :cliente
end

app/models/proveedor_servicio.rb
class ProveedorServicio < ApplicationRecord
  belongs_to :categoria
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/publicidad.rb
class Publicidad < ApplicationRecord
  belongs_to :cliente
end

app/models/subcategorium.rb
class Subcategorium < ApplicationRecord
  belongs_to :categorias
end

app/controllers/pagos_publicidads_controller.rb
class PagosPublicidadsController < ApplicationController
  before_action :set_pagos_publicidad, only: [:show, :edit, :update, :destroy]

  # GET /pagos_publicidads
  # GET /pagos_publicidads.json
  def index
    @pagos_publicidads = PagosPublicidad.all
  end

  # GET /pagos_publicidads/1
  # GET /pagos_publicidads/1.json
  def show
  end

  # GET /pagos_publicidads/new
  def new
    @pagos_publicidad = PagosPublicidad.new
  end

  # GET /pagos_publicidads/1/edit
  def edit
  end

  # POST /pagos_publicidads
  # POST /pagos_publicidads.json
  def create
    @pagos_publicidad = PagosPublicidad.new(pagos_publicidad_params)

    respond_to do |format|
      if @pagos_publicidad.save
        format.html { redirect_to @pagos_publicidad, notice: 'Pagos publicidad was successfully created.' }
        format.json { render :show, status: :created, location: @pagos_publicidad }
      else
        format.html { render :new }
        format.json { render json: @pagos_publicidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagos_publicidads/1
  # PATCH/PUT /pagos_publicidads/1.json
  def update
    respond_to do |format|
      if @pagos_publicidad.update(pagos_publicidad_params)
        format.html { redirect_to @pagos_publicidad, notice: 'Pagos publicidad was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagos_publicidad }
      else
        format.html { render :edit }
        format.json { render json: @pagos_publicidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagos_publicidads/1
  # DELETE /pagos_publicidads/1.json
  def destroy
    @pagos_publicidad.destroy
    respond_to do |format|
      format.html { redirect_to pagos_publicidads_url, notice: 'Pagos publicidad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagos_publicidad
      @pagos_publicidad = PagosPublicidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagos_publicidad_params
      params.require(:pagos_publicidad).permit(:cliente_id, :promocionEventos_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/encuesta_helper.rb
module EncuestaHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/pagos_publicidads_helper.rb
module PagosPublicidadsHelper
end

app/helpers/portada_helper.rb
module PortadaHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/views/pagos_publicidads/_form.html.erb
<%= form_with(model: pagos_publicidad, local: true) do |form| %>
  <% if pagos_publicidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pagos_publicidad.errors.count, "error") %> prohibited this pagos_publicidad from being saved:</h2>

      <ul>
      <% pagos_publicidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.text_field :cliente_id, id: :pagos_publicidad_cliente_id %>
  </div>

  <div class="field">
    <%= form.label :promocionEventos_id %>
    <%= form.text_field :promocionEventos_id, id: :pagos_publicidad_promocionEventos_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pagos_publicidads/edit.html.erb
<h1>Editing Pagos Publicidad</h1>

<%= render 'form', pagos_publicidad: @pagos_publicidad %>

<%= link_to 'Show', @pagos_publicidad %> |
<%= link_to 'Back', pagos_publicidads_path %>

app/views/pagos_publicidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagos Publicidads</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Promocioneventos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pagos_publicidads.each do |pagos_publicidad| %>
      <tr>
        <td><%= pagos_publicidad.cliente %></td>
        <td><%= pagos_publicidad.promocionEventos %></td>
        <td><%= link_to 'Show', pagos_publicidad %></td>
        <td><%= link_to 'Edit', edit_pagos_publicidad_path(pagos_publicidad) %></td>
        <td><%= link_to 'Destroy', pagos_publicidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pagos Publicidad', new_pagos_publicidad_path %>

app/views/pagos_publicidads/new.html.erb
<h1>New Pagos Publicidad</h1>

<%= render 'form', pagos_publicidad: @pagos_publicidad %>

<%= link_to 'Back', pagos_publicidads_path %>

app/views/pagos_publicidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @pagos_publicidad.cliente %>
</p>

<p>
  <strong>Promocioneventos:</strong>
  <%= @pagos_publicidad.promocionEventos %>
</p>

<%= link_to 'Edit', edit_pagos_publicidad_path(@pagos_publicidad) %> |
<%= link_to 'Back', pagos_publicidads_path %>